// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_XY6Djnre2yhsjQRuTk14Frvv5varCwY',
    appId: '1:34404962504:web:e620cc79e4d41864bd95fd',
    messagingSenderId: '34404962504',
    projectId: 'online-voting-system-d490b',
    authDomain: 'online-voting-system-d490b.firebaseapp.com',
    databaseURL: 'https://online-voting-system-d490b-default-rtdb.firebaseio.com',
    storageBucket: 'online-voting-system-d490b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYvCkFnu4mvbN6HZBxYRiy_zBubY1lFGs',
    appId: '1:34404962504:android:926da6f416485de4bd95fd',
    messagingSenderId: '34404962504',
    projectId: 'online-voting-system-d490b',
    databaseURL: 'https://online-voting-system-d490b-default-rtdb.firebaseio.com',
    storageBucket: 'online-voting-system-d490b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs8gcnjREaswNHj-JTUpw71KrFXIJOiUQ',
    appId: '1:34404962504:ios:c36c31b5471b35c1bd95fd',
    messagingSenderId: '34404962504',
    projectId: 'online-voting-system-d490b',
    databaseURL: 'https://online-voting-system-d490b-default-rtdb.firebaseio.com',
    storageBucket: 'online-voting-system-d490b.appspot.com',
    iosClientId: '34404962504-qs9pjnua6ocua3rotmfmpva1s291vm1o.apps.googleusercontent.com',
    iosBundleId: 'com.mes.voting.onlineVotingSystem',
  );
}
